// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	PriceInCents int32              `json:"price_in_cents"`
	Quantity     int32              `json:"quantity"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
